### PR TITLE
Update cookbook_gallery.txt

### LINKED ISSUE #165: Update Gallery with new Cookbook
### Root Repository Name

interactive-sentinel-2-cookbook

### Did you check if your contribution would be better suited as an addition to an existing Cookbook, before generating a new one?

yes

### Additional comments

This Project Pythia Cookbook provides a recipe for building an interactive dashboard for the Sentinel-2 L2A satellite imagery using the holoviews ecosystem.

### PR DESCRIPTION
**Pull request by jukent**
Closes #165 Adds `interactive-sentinel-2-cookbook`

https://github.com/ProjectPythia/interactive-sentinel-2-cookbook
https://projectpythia.org/interactive-sentinel-2-cookbook/README.html

### CODE REVIEW

**Review by r-ford — APPROVED** [review]
With https://github.com/ProjectPythia/interactive-sentinel-2-cookbook/pull/4 merged, I think this is ready for the gallery.

**Comment by clyne** [comment]
@r-ford when I execute this cookbook, both through binder and locally, there are a couple of cells that generate warnings:

The call to `da = da.compute()` spits out:

```
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/rasterio/warp.py:344: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  _reproject(
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/rasterio/warp.py:344: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  _reproject(
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/dask/core.py:129: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/dask/core.py:129: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/dask/core.py:129: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/dask/core.py:129: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/dask/core.py:129: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/dask/core.py:129: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/dask/core.py:129: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
```

Also, the definition of the function plot_band generates:

```
/Users/clyne/mambaforge/envs/is2-cookbook-dev/lib/python3.11/site-packages/holoviews/plotting/bokeh/plot.py:987: UserWarning: found multiple competing values for 'toolbar.active_drag' property; using the latest value
  layout_plot = gridplot(
```

Are you seeing these messages? Should our CI be catching these? Can they be fixed?

**Comment by clyne** [comment]
@r-ford, please forgive my weak GitHub kung fu, but what is the best practice for providing comments regarding the code, since the code is on a separate repo from this PR? Thanks!!

**Comment by r-ford** [comment]
@clyne 

I'm not sure if there is a better way, but I just opened an issue and PR on the cookbook repo.

I'm not familiar with the warnings, but maybe @pritamd47 knows. I can take a closer look later today.

**Review by clyne — COMMENTED** [review]
Waiting for author to address issues opened [here](https://github.com/ProjectPythia/interactive-sentinel-2-cookbook/issues/5).

**Review by clyne — APPROVED** [review]

**Pull request merged**
