### PR TITLE
Update cookbook gallery per #78

### LINKED ISSUE #78: Update Gallery with new Cookbook
### Root Repository Name

intake-cookbook

### Did you check if your contribution would be better suited as an addition to an existing Cookbook, before generating a new one?

_No response_

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by jukent**
Update cookbook gallery as requested in #78. Closes #78.

### CODE REVIEW

**Comment by jukent** [comment]
Okay @jnmorley Now that your config is updated we'll rerun this job

**Comment by jukent** [comment]
I just pushed a correction to the thumbnail image (the path was .png instead of .svg). I'll change the author too.

**Comment by jukent** [comment]
I'm waiting for the intake-cookbook repo to have fully built the changes before I rerun this job.

**Comment by jukent** [comment]
LGTM

**Review by brian-rose — APPROVED** [review]
Me too! Good to go.

**Pull request merged**
