### PR TITLE
grab binder link from config

### PR DESCRIPTION
**Pull request by jukent**
Addresses #102 
Grabs the Binder link for the gallery card badge from each Cookbook repository's README

### CODE REVIEW

**Comment by brian-rose** [comment]
Hmm the links on the preview are still broken: https://cookbooks.projectpythia.org/_preview/103/

**Comment by jukent** [comment]
Ahh it's because not all of the repositories have the Binder link on the same line. I'm going to enforce that it is consistent.

**Comment by jukent** [comment]
I don't see it explicitly listed in the config file?

https://github.com/ProjectPythia/HRRR-AWS-cookbook/blob/main/_config.yml

**Comment by jukent** [comment]
The first link just says that our root path is "http://binder.mypythia.org" -  which is useful but doesn't quite get me there. I'm trying to parse the 2nd link, but its a bit dense for me to be able to work through quickly

I have to leave in 15 minutes and can't return to this problem till tonight.

**Comment by jukent** [comment]
It looks like that workflow uses something called "parse_config" but it doesn't have any of the logic for doing so in it. I'll try to track that down.

Here is my first attempt at using the config file:
```
repo = "hrrr-aws-cookbook"
config_url = f"https://raw.githubusercontent.com/ProjectPythia/{repo}/main/_config.yml"
config = urllib.request.urlopen(config_url)
config_dict = yaml.safe_load(config)

root = config_dict["sphinx"]["config"]["html_theme_options"]["launch_buttons"]["binderhub_url"]
end = f"/v2/gh/ProjectPythia/{repo}.git/main"
url = root + end```

but I'm not confident in it, just a first stab.

**Comment by jukent** [comment]
https://github.com/ProjectPythia/cesm-lens-aws-cookbook
This cookbook's README binder link (https://aws-uswest2-binder.pangeo.io/v2/gh/ProjectPythia/cesm-lens-aws-cookbook/main?labpath=notebooks)  doesn't seem to follow the root in the config file?

**Comment by jukent** [comment]
Okay well it is working in the preview now will grabbing the files from the README. I like the idea of getting them from the config because a dictionary is more stable than assuming something is on line 6 - but I think the logic of how the config turns into the correct link is a little beyond me in the time I have right now. I'm swamped with a lot of stuff. This solution will work at least until we get past AGU. If someone else who understands the Binder link generation better wants to work on, feel free

**Comment by brian-rose** [comment]
@jukent your code above to grab the URL from the config file looks good to me. I just pushed an update to this PR that uses it. 

Also hoping this fixes a glitch I can see in the preview where the links are there but the badge images are missing.

**Comment by brian-rose** [comment]
This seems to work well: https://cookbooks.projectpythia.org/_preview/103/

**Review by brian-rose — APPROVED** [review]

**Comment by jukent** [comment]
@brian-rose okay great. I'm still confused about the cesm-lens-aws one having a different root path though.

**Comment by brian-rose** [comment]
@jukent It may just be an error in that repo. The two paths should be the same, and I'd like to develop some automation to ensure that. 

So when we want to switch between different Binder services, it's really just updating the config file and that's it.

**Comment by brian-rose** [comment]
I fixed the issue in the CESM-LENS repo. 

@jukent if you're happy with this PR, please merge when you're ready.

**Comment by jukent** [comment]
@brian-rose The binder badge doesn't render now.

**Comment by brian-rose** [comment]
> @brian-rose The binder badge doesn't render now.

@jukent I'm not sure what you're seeing? The badges render fine in the preview for this PR.

**Comment by jukent** [comment]
Screen Shot 2022-12-07 at 10 38 07 AM

Each gallery card looks like this on my end. It looks correct on your machine? @brian-rose

**Comment by brian-rose** [comment]
I just tried in two different browsers, Safari and Firefox on a Mac laptop, and got the same result, looking at https://cookbooks.projectpythia.org/_preview/103/

**Comment by jukent** [comment]
Okay. Then I'm okay with merging. Let's see if we can get another person to look and see if it is correct on their machine too first?

**Comment by brian-rose** [comment]
Suggest merging now, and we'll see if the same weirdness shows up on the main gallery page at https://cookbooks.projectpythia.org

If so, we'll fix it.

**Comment by jukent** [comment]
It works for me on Firefox and Safari, but not Chrome or Chrome Beta. Could you try Chrome too? But yes we can merge it, and I'll just use Firefox during my demonstrations at AGU if it isn't fixed in time.

**Comment by brian-rose** [comment]
@jukent I confirm that I see the same badge failure on https://cookbooks.projectpythia.org/ on Chrome, but not on my other browsers!

Curious.

The badges on individual README pages (e.g. https://github.com/ProjectPythia/cesm-lens-aws-cookbook) look fine in Chrome.

**Comment by brian-rose** [comment]
I'll open a new issue for this.

**Pull request merged**
