### PR TITLE
Add paleoPCA-cookbook

### PR DESCRIPTION
**Pull request by brian-rose**
This PR adds the paleoPCA-cookbook to the gallery. This was a 2024 hackathon contribution and had gone through a thorough review

### CODE REVIEW

**Comment by brian-rose** [comment]
Ah, I see now that this is breaking because there is no `abstract` field in the [paleoPCA-cookbook CITATION.cff file](https://github.com/ProjectPythia/paleoPCA-cookbook/blob/main/CITATION.cff).

Need to fix that first.

**Comment by brian-rose** [comment]
This is working and ready to go!

**Review by jukent — APPROVED** [review]
Looks great!
Do you foresee adding any more notebooks to the Cookbook?

**Review by ktyle — APPROVED** [review]

**Comment by brian-rose** [comment]
> Looks great! Do you foresee adding any more notebooks to the Cookbook?

That would be a question for the lead author @khider. There are some [open issues](https://github.com/ProjectPythia/paleoPCA-cookbook/issues) describing future enhancements of the existing notebook.

**Comment by brian-rose** [comment]
I'll merge this, and we can celebrate one more published product from our 2024 hackathon!

**Pull request merged**
